apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  namespace: { { .Values.namespace.name } }
  name: techtrends
spec:
  ports:
    - port: { { .Values.service.port } }
      protocol: TCP
      targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP