namespace:
  name: prod

service:
  port: 7111
  protocol: TCP
  type: ClusterIP
image:
  repository: techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi
