namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: oberlin/techtrends
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: "regcred"

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
ports:
  - name: containerPort
    containerPort: 3111
livenessProbe:
  httpGet:
    path: "/healthz"
    port: 3111
    scheme: HTTP

redinessProbe:
  httpGet:
    path: "/healthz"
    port: 3111
    scheme: HTTP