namespace:
  name: staging

service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: oberlin/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi