name: TechTrends - Package with Docker

on:
  push:
    branches:
      - 'master'
defaults:
  run:
    working-directory: ./project/techtrends

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: techtrends:latest
        #run: docker build ./ --file Dockerfile --tag techtrends:latest